{% set name = "haystack-ai" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/haystack_ai-{{ version }}.tar.gz
  sha256: e51e4c15e71a0a91e1bf7e5bd7868dc923e1c6f632bab60c0dc4cb76cc35e4ba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.8.0
    - pip
  run:
    - python >=3.8
    - pandas
    - tqdm
    - tenacity
    - lazy-imports
    - openai >=1.1.0
    - jinja2
    - posthog
    - pyyaml
    - more-itertools
    - networkx
    - typing-extensions >=4.7
    - requests
    - numpy <2.0.0
    - python-dateutil
    - haystack-experimental

test:
  imports:
    - haystack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepset-ai/haystack
  summary: LLM framework to build customizable, production-ready LLM applications. Connect components (models, vector DBs, file converters) to pipelines or agents that can interact with your data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - silvanocerza
