{% set name = "haystack-ai" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/haystack_ai-{{ version }}.tar.gz
  sha256: ef3c21b98f49aeef367788c865d9464fa824abd4d71fb966b63218fe75363f2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.8.0
    - pip
  run:
    - python >=3.8
    - pandas
    - haystack-bm25
    - tqdm
    - tenacity
    - lazy-imports
    - openai >=1.1.0
    - jinja2
    - posthog
    - pyyaml
    - more-itertools
    - networkx
    - typing-extensions >=4.7
    - trafilatura
    - requests
    - numpy
    - python-dateutil

test:
  imports:
    - haystack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepset-ai/haystack
  summary: LLM framework to build customizable, production-ready LLM applications. Connect components (models, vector DBs, file converters) to pipelines or agents that can interact with your data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - masci
    - silvanocerza
