{% set name = "haystack-ai" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/haystack_ai-{{ version }}.tar.gz
  sha256: 8be007dbf95a8811d6abe42747bba8d8454944a8fe603c13c3c7643b2d16faf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.8.0
    - pip
  run:
    - python >=3.8
    - pandas
    - tqdm
    - tenacity
    - lazy-imports
    - openai >=1.1.0
    - jinja2
    - posthog
    - pyyaml
    - more-itertools
    - networkx
    - typing-extensions >=4.7
    - requests
    - numpy <2.0.0
    - python-dateutil
    - haystack-experimental

test:
  imports:
    - haystack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepset-ai/haystack
  summary: LLM framework to build customizable, production-ready LLM applications. Connect components (models, vector DBs, file converters) to pipelines or agents that can interact with your data.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-risch
