schema_version: 1

context:
  name: haystack-ai
  version: 2.28.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/haystack_ai-${{ version }}.tar.gz
  sha256: 723d8e1ba06b214d5dcba8712d2dd7f9134b949b1d3e91dc92a14af33c893823

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=${{ python_min }}
    - hatchling >=1.8.0
    - pip
  run:
    - python >=${{ python_min }}
    - docstring_parser
    - filetype
    - haystack-experimental
    - jinja2
    - jsonschema
    - lazy-imports
    - more-itertools
    - networkx
    - numpy
    - openai >=1.99.2
    - posthog !=3.12.0
    - pydantic
    - python-dateutil
    - pyyaml
    - tenacity !=8.4.0
    - tqdm
    - typing_extensions >=4.7
    - markupsafe
    - httpx
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - haystack
      pip_check: true

about:
  summary: LLM framework to build customizable, production-ready LLM applications. Connect components (models, vector DBs, file converters) to pipelines or agents that can interact with your data.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/deepset-ai/haystack

extra:
  recipe-maintainers:
    - julian-risch
    - moritzwilksch
