schema_version: 1

context:
  name: haystack-ai
  version: "2.25.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/haystack_ai-${{ version }}.tar.gz
  sha256: e1be0ed36a379605c2cfbb7140585b77c56e2aa053339ab5d1d75826b48c44ec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=${{ python_min }}
    - hatchling >=1.8.0
    - pip
  run:
    - python >=${{ python_min }}
    - docstring-parser
    - filetype
    - haystack-experimental
    - jinja2
    - jsonschema
    - lazy-imports
    - more-itertools
    - networkx
    - numpy
    - openai >=1.99.2
    - posthog !=3.12.0
    - pydantic
    - python-dateutil
    - pyyaml
    - requests
    - tenacity !=8.4.0
    - tqdm
    - typing-extensions >=4.7

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - haystack
      pip_check: true

about:
  summary: LLM framework to build customizable, production-ready LLM applications. Connect components (models, vector DBs, file converters) to pipelines or agents that can interact with your data.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/deepset-ai/haystack

extra:
  recipe-maintainers:
    - julian-risch
    - moritzwilksch
